version: '3'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin_password
      - DOCKER_INFLUXDB_INIT_ORG=IIITA
      - DOCKER_INFLUXDB_INIT_BUCKET=bda
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    volumes:
      - ./influx-volume:/var/lib/influxdb2
    networks:
      - bda_project
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "1000"
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    volumes:
      - ./grafana-data:/var/lib/grafana
    networks:
      - bda_project

networks:
  bda_project: